sudo: required

services:
  - docker

before_install:
  - docker build -t mintedguy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mintedguy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-512590308957'
  bucket_path: 'docker-react'

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
